INSERT INTO "public"."Spice" (name) VALUES ('Alho'),
('Cebola'),
('Sal-refinado'),
('Sal-rosa'),
('Sal-marinho'),
('Louro'),
('Pimenta-do-Reino'),
('Tempero-Baiano'),
('Açafrão'),
('Coentro'),
('Salsa'),
('Cebolinha'),
('Alecrim'),
('Tomilho'),
('Manjericão'),
('Orégano'),
('Pimenta-Calabresa'),
('Azeite');