INSERT INTO "public"."Gauges" (gauge, description) VALUES ('cs', 'Colher(es) de sopa'),
('csb', 'Colher(es) de sobremesa'),
('cc', 'Colher(es) de chá'),
('ccf', 'Colher(es) de café'),
('xc', 'Xícara(s) de chá'),
('xcf', 'Xícara(S) de café'),
('cr', 'Copo(s) de requeijão'),
('cap', 'Copo(s) americano pequeno'),
('cag', 'Copo(s) americano grande'),
('Tbsp', 'Tablespoon'),
('Tsp', 'Teaspoon'),
('Oz', 'Ounce'),
('fl. Oz', 'Fluid Ounce'),
('C', 'Cup'),
('Qt', 'Quart'),
('Pt', 'Pint'),
('gal', 'Gallon'),
('mL', 'Mililiter'),
('g', 'Grams'),
('Kg', 'Kilograms'),
('L', 'Liter(s)');