INSERT INTO "public"."Ingredients" (name) VALUES ('Azeite de Dendê <3'),
('Camarão'),
('Caranguejo'),
('Leite de Coco'),
('Graviola'),
('Mandioca'),
('Milho'),
('Carne Seca'),
('Pequi'),
('Arroz'),
('Feijão'),
('Ovo'),
('Palmito'),
('Banana'),
('Batata'),
('Fava'),
('Lentilha'),
('Couve'),
('Repolho');